apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "6.16.6"
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
      valuesKey: values-promtail.yaml
