promtail:
  config:
    server:
      http_listen_port: 3101
      grpc_listen_port: 9095
    clients:
      - url: "http://loki:3100/loki/api/v1/push" # forwarding to Loki
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              __path__: /var/log/*log
