apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: monitoring
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 127.0.0.1:4317
            max_recv_msg_size_mib: 10
          http:
            endpoint: 127.0.0.1:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      k8sattributes:
        extract:
          metadata:
          - service.instance.id
          - service.name
          - service.namespace
          - cloud.availability_zone
          - cloud.region
          - container.name
          - deployment.environment.name
          - k8s.cluster.name
          - k8s.container.name
          - k8s.cronjob.name
          - k8s.daemonset.name
          - k8s.deployment.name
          - k8s.job.name
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.replicaset.name
          - k8s.statefulset.name
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      resource:
        attributes:
          - key: cluster
            value: "service"
            action: upsert

    exporters:
      debug:
        verbosity: detailed
      otlp/jaeger:
        endpoint: "jaeger-collector.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      otlphttp/prometheus:
        endpoint: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/otlp"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          exporters:
            - otlp/jaeger
          processors:
            - batch
            - memory_limiter
          receivers:
            - otlp
        metrics:
          exporters:
            - otlphttp/prometheus
          processors:
            - batch
            - k8sattributes
            - memory_limiter
            - resource
          receivers:
            - otlp
        logs:
          exporters:
            - debug
          processors:
            - batch
            - memory_limiter
          receivers:
            - otlp
