---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demanda-sqnc-attachment-api
  namespace: demanda
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
    - name: ipfs
    - name: demanda-identity-service
  chart:
    spec:
      chart: sqnc-attachment-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: 2.0.0
  valuesFrom:
    - kind: ConfigMap
      name: demanda-values
      valuesKey: values-attachment-api.yaml
    - kind: Secret
      name: demanda-attachment-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: demanda-internal-client-secret
      valuesKey: key
      targetPath: auth.internalClientSecret
    - kind: Secret
      name: demanda-keys
      valuesKey: account_seed
      targetPath: userUri
  interval: 10m0s
