provisionDataStore:
  cassandra: false
  elasticsearch: true
storage:
  type: elasticsearch
elasticsearch:
  master:
    replicaCount: 3
    persistence:
      storageClass: managed-csi-premium
      size: 50Gi
  data:
    replicaCount: 3
    persistence:
      storageClass: managed-csi-premium
      size: 80Gi
agent:
  enabled: true
collector:
  enabled: true
query:
  enabled: true
  basePath: /jaeger
  pathType: Prefix
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    ingressClassName: nginx-monitoring
    enabled: true
    hosts:
      - monitoring.sqnc-stage.com
  oAuthSidecar:
    enabled: true
    resources: {}
    image:
      registry: quay.io
      repository: oauth2-proxy/oauth2-proxy
      tag: v7.8.1
    pullPolicy: IfNotPresent
    containerPort: 4180
    args:
      - --config
      - /etc/oauth2-proxy/oauth2-proxy.cfg
      - --client-secret
      - "$(client-secret)"
      - --cookie-secret
      - "$(cookie-secret)"
    extraEnv:
      - name: client-secret
        valueFrom:
          secretKeyRef:
            name: grafana-client-secret
            key: grafana-client-secret
      - name: cookie-secret
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-cookie-secret
            key: secret
    extraConfigmapMounts: []
    extraSecretMounts: []
    config: |-
      provider = "keycloak-oidc"
      http_address = ":4180"
      upstreams = ["http://jaeger-query.monitoring.svc.cluster.local:16686"]
      redirect_url = "https://monitoring.sqnc-stage.com/jaeger/oauth2/callback"
      client_id = "grafana"
      oidc_issuer_url = "https://auth.sqnc-stage.com/realms/monitoring"
      email_domains = "digicatapult.org.uk"
      oidc_groups_claim = "groups"
      user_id_claim = "preferred_username"
      skip_provider_button = "true"
      cookie_path = "/jaeger"
      cookie_secure = "true"
      cookie_domain = "monitoring.sqnc-stage.com"
      cookie_httponly = "true"
      cookie_refresh = "1h"
      cookie_expire = "168h"