provisionDataStore:
  cassandra: false
  elasticsearch: true
storage:
  type: elasticsearch
elasticsearch:
  master:
    replicaCount: 3
    persistence:
      storageClass: managed-csi-premium
      size: 50Gi
  data:
    replicaCount: 3
    persistence:
      storageClass: managed-csi-premium
      size: 80Gi
agent:
  enabled: true
collector:
  enabled: true
query:
  enabled: true
  basePath: /jaeger
  pathType: Prefix
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    ingressClassName: nginx-monitoring
    enabled: true
    hosts:
      - monitoring.sqnc-stage.com
  oAuthSidecar:
    enabled: true
    resources: {}
    image:
      registry: quay.io
      repository: oauth2-proxy/oauth2-proxy
      tag: v7.8.1
    pullPolicy: IfNotPresent
    containerPort: 4180
    args:
    - --provider=keycloak-oidc
    - --http-address=:4180
    - --upstream=http://jaeger-query.monitoring.svc.cluster.local:16686
    - --redirect-url=https://monitoring.sqnc-stage.com/jaeger/oauth2/callback
    - --client-id=grafana
    - --oidc-issuer-url=https://auth.sqnc-stage.com/realms/monitoring
    - --email-domain=digicatapult.org.uk
    - --oidc-groups-claim=groups
    - --user-id-claim=preferred_username
    - --skip-provider-button=true
    - --cookie-path=/jaeger
    - --cookie-secure=true
    - --cookie-httponly=true
    - --cookie-refresh=1h
    - --cookie-expire=168h
    - --cookie-secret=$(cookie-secret)
    - --code-challenge-method=S256
    - --standard-logging=true
    - --show-debug-on-error=true
    extraEnv:
      - name: OAUTH2_PROXY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: grafana-client-secret
            key: grafana-client-secret
      - name: cookie-secret
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-cookie-secret
            key: secret
    extraConfigmapMounts: []
    extraSecretMounts: []