logLevel: info
selfAddress: 5Gh5cFC3sPS7pK8SN41Ytp6VFsMyPpvKxtrrcLpkf19u9W83
externalSqncNode:
  host: sqnc-node
  port: 9944
auth:
  clientId: 'l3'
  publicIdpOrigin: "https://auth.dsch-l3.com"
  internalIdpOrigin: "http://keycloak.keycloak.svc.cluster.local"
  idpPathPrefix: ""
  oauth2Realm: capacity
  internalRealm: capacity-internal
ingress:
  enabled: true
  ingressClassName: nginx-capacity
  hostname: capacity.dsch-l3.com
node:
  enabled: false
postgresql:
  global:
    imagePullSecrets:
      - name: dockerhub
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: capacity
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
global:
  imagePullSecrets:
    - name: dockerhub
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
