---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alice-sqnc-matchmaker-api
  namespace: alice
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  test:
    enable: true
  dependsOn:
    - name: alice-ipfs
  chart:
    spec:
      chart: sqnc-matchmaker-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: "3.0.6"
  valuesFrom:
    - kind: ConfigMap
      name: alice-values
      valuesKey: values-sqnc-matchmaker-api.yaml
  interval: 10m0s
