global:
  imagePullSecrets:
    - name: dockerhub
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/keycloak
replicas: 0
keycloakConfigCli:
  image:
    repository: bitnamilegacy/keycloak-config-cli
production: true
proxyHeaders: forwarded
ingress:
  enabled: true
  ingressClassName: nginx-keycloak
  hostname: auth.dsch-l3.com
adminIngress:
  enabled: true
  ingressClassName: nginx-keycloak
  hostname: auth.dsch-l3.com
auth:
  adminUser: "admin"
extraEnvVars:
  - name: KC_HOSTNAME_ADMIN
    value: "https://auth.dsch-l3.com/"
  - name: KC_HOSTNAME
    value: "https://auth.dsch-l3.com/"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: keycloak
    relabelings:
      - action: replace
        sourceLabels: [namespace]
        targetLabel: kubernetes_namespace
externalDatabase:
  host: keycloak-cnpg-rw.keycloak.svc.cluster.local
  port: 5432
  database: keycloak
  user: keycloak
  existingSecret: keycloak-cnpg-superuser-creds
  existingSecretPasswordKey: password
postgresql:
  enabled: false
podAnnotations:
    instrumentation.opentelemetry.io/inject-java: "monitoring/java-instrumentation"
