apiVersion: v1
data:
  address: aHR0cHM6Ly9wcm9kLTYzLnVrc291dGgubG9naWMuYXp1cmUuY29tOjQ0My93b3JrZmxvd3MvN2JiODcyMmEyYTEzNGZmOWI1MWE4ZjIyMDcxMmExNmEvdHJpZ2dlcnMvbWFudWFsL3BhdGhzL2ludm9rZT9hcGktdmVyc2lvbj0yMDE2LTA2LTAxJnNwPSUyRnRyaWdnZXJzJTJGbWFudWFsJTJGcnVuJnN2PTEuMCZzaWc9TTVZVVgxMzFYc2wybmJmYkF2MnlUS0k5Ync0U2FHaTNpWU5ScktHM3hpNA==
kind: Secret
metadata:
  creationTimestamp: null
  name: teams-webhook
  namespace: monitoring
