apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel
  namespace: monitoring
spec:
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.94.2"
      sourceRef:
        kind: HelmRepository
        name: otel
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
      valuesKey: values-otel.yaml
