logLevel: info
selfAddress: 5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y
externalSqncNode:
  host: charlie-node-sqnc-node-0
  port: 9944
auth:
  clientId: sequence
  publicIdpOrigin: http://localhost:3080
  internalIdpOrigin: http://keycloak.keycloak.svc.cluster.local
  idpPathPrefix: /auth
  oauth2Realm: charlie
  internalRealm: charlie-internal
ingress:
  hostname: localhost
  paths:
    - path: /charlie/(v1/members(/.*)?)
      pathType: Prefix
    - path: /charlie/(v1/self(/.*)?)
      pathType: Prefix
    - path: /alice/(v1/roles(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
node:
  enabled: false
postgresql:
  auth:
    password: postgres
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
