# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
controller:
  updateStrategy:
    type: Recreate
  allowSnippetAnnotations: true
  enableAnnotationValidations: true
  config:
    annotations-risk-level: Critical
  watchIngressWithoutClass: true
  extraArgs:
    publish-status-address: localhost
  publishService:
    enabled: false
  ingressClassResource:
    name: nginx
    electionID: nginx-leader
    controllerValue: k8s.io/ingress-nginx
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
  nodeSelector:
    ingress-ready: "true"
    kubernetes.io/os: linux
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Equal
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Equal
  containerPorts:
    http: 80
    https: 443
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
  admissionWebhooks:
    enabled: false
