# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
controller:
  watchIngressWithoutClass: true
  scope:
    enabled: true
  ingressClassResource:
    name: nginx-optimiser
    default: false
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      external-dns.alpha.kubernetes.io/hostname: optimiser.dsch-l3.com
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/common-name: optimiser.dsch-l3.com
  extraArgs:
    default-ssl-certificate: "optimiser/optimiser-dsch-l3-com-prod-tls"
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Equal
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Equal
  containerPort:
    http: 80
    https: 443
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: optimiser
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
