node:
  chainSpecConfigMap: chainspec
  chain: ""
  role: validator
  dataVolumeSize: 100Gi
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  keys:
    - type: "babe"
      scheme: "sr25519"
    - type: "gran"
      scheme: "ed25519"
  flags:
    - "--rpc-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"
    - "--prometheus-external"
    - "--state-pruning=2500000"
    - "--database=paritydb"
    - "--bootnodes '/dns4/magenta-sqnc-node-0-rc-p2p.demanda.svc.cluster.local/tcp/30333/p2p/12D3KooWEFWQaDRGkX1s7apijUT55CQGPELbzCphZwbFe3YFLhC5'"
  serviceMonitor:
    enabled: true
    namespace: match2
storageClass: managed-csi-premium
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - sqnc-node
        topologyKey: kubernetes.io/hostname
        namespaceSelector: {}
tests:
  osShell:
    image:
      repository: bitnamilegacy/os-shell
kubectl:
  image:
    repository: bitnamilegacy/kubectl