---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: managed-csi-premium
  managed:
    roles:
    - name: app
      createdb: true
      login: true
    - name: keycloak
      ensure: present
      login: true
      superuser: false
      createdb: true
      createrole: true
      inherit: false
      replication: false
      bypassrls: false
      connectionLimit: 4
      validUntil: "2050-01-01T00:00:00Z"
      inRoles:
        - pg_monitor
        - pg_signal_backend
      passwordSecret:
        name: keycloak-postgres-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
  namespace: keycloak
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: cluster
  databaseReclaimPolicy: delete
