apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  interval: 1m
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  chart:
    spec:
      chart: jaeger
      version: "3.4.0"
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
      valuesKey: values-jaeger.yaml
