---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cyan-node
  namespace: order
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
  test:
    enable: true
  chart:
    spec:
      version: 7.1.5
      chart: sqnc-node
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: order-values
      valuesKey: values-cyan.yaml
    - kind: Secret
      name: cyan-keys
      valuesKey: babe_seed
      targetPath: node.keys[0].seed
    - kind: Secret
      name: cyan-keys
      valuesKey: grandpa_seed
      targetPath: node.keys[1].seed
    - kind: Secret
      name: cyan-keys
      valuesKey: node_id
      targetPath: node.customNodeKey
  interval: 10m
