---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: monitoring
spec:
  install:
    remediation:
      retries: -1
  releaseName: redis
  chart:
    spec:
      version: 20.11.4
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
  interval: 10m
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
      valuesKey: values-redis.yaml
