---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: match2-sqnc-attachment-api
  namespace: match2
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
    - name: ipfs
    - name: match2-identity-service
    - name: match2-matchmaker-api
  chart:
    spec:
      chart: sqnc-attachment-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: 2.0.0
  valuesFrom:
    - kind: ConfigMap
      name: match2-values
      valuesKey: values-attachment-api.yaml
    - kind: Secret
      name: match2-attachment-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: match2-keys
      valuesKey: account_seed
      targetPath: userUri
  interval: 10m0s
