logLevel: debug
externalSqncNode:
  host: sqnc-node
  port: 9944
externalSqncIpfs:
  host: ipfs-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: match2-identity-service-sqnc-identity-service
  port: 3000
auth:
  clientId: 'sqnc'
  publicIdpOrigin: "https://auth.sqnc-stage.com/"
  internalIdpOrigin: "http://keycloak.keycloak.svc.cluster.local"
  idpPathPrefix: /auth
  oauth2Realm: match2
  internalRealm: match2-internal
ingress:
  enabled: true
  ingressClassName: nginx-match2
  hostname: match2.sqnc-stage.com
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 15Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: match2
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
