---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: charlie-ipfs
  namespace: charlie
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: charlie-node
  chart:
    spec:
      chart: sqnc-ipfs
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: "4.0.37"
  valuesFrom:
  - kind: ConfigMap
    name: charlie-values
    valuesKey: values-sqnc-ipfs.yaml
  interval: 10m
