apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:5bnJRrh7mQhphLSQoj9joERpV030+lsXLBDk4AGU1zBkV/Ov9uB7U+pkcudjyphq2fvkM2OcPuCfW3JOtR3WcTchpmhpyiNmBqI2xsalkdC72qIkkH2Y7GrHFWZ130tF,iv:YQqZBSmEDPbHW0ZlrNSTGo1C0lhFN/p2a5J1vHIlev8=,tag:avMFBpndM0hHvIevjfiJmA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: green-optimiser-authority-account
    namespace: optimiser
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-12T14:55:52Z"
    mac: ENC[AES256_GCM,data:/5SzqBrEUIEaGaR1oN3QDelcAmO3dh9ReZi/QvVr7lyHSIG86B4PAotc03XXCiK2HGAU+FUA2rfosxPn94JlwtK4K0W0Ph78gmK2KE76fAs4iFIqfUgMiOSn+hW5shCtl/EquRNTIIpQsM1MbNnnwQccPhr7UE1UM7CcrQ89BW4=,iv:bj04usVoDwXssC59OCQ4f2k9GusprHfnoxaHT+QG/eQ=,tag:SZEkhLy6omqazDAC/0wr2w==,type:str]
    pgp:
        - created_at: "2025-03-12T14:55:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWK9rONmXZEsSAQdAARJF8gzJNDu6Y6U3iCWVeGN816vc/ppiChKheYOCGXww
            kDYEkirJYR/4ShvNzmGJNgpzVfbVTq1ihi7Cvm453Y9L82ZkMz1Iiks12BoAC9QC
            1GgBCQIQoYluZE6ZZBLNVfQSOyuDgbG8TfRYqkuO6+DzvA850YzOZK5xCRrv2xbN
            981JBH7d/btLHzo4SrCFfQMOBlKMXngE5mXaLPn8hdtMiDWZ7F1oQ1nfRoW9KSBv
            +Bwz20wc2Ev+aA==
            =/bFh
            -----END PGP MESSAGE-----
          fp: BC3A767578FF432C7414DE6A73A07B99E207F7AF
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
