apiVersion: v1
data:
    password: ENC[AES256_GCM,data:x1VeZxZlRNZV5PGIU4QGFOkWdUOO3Vv2,iv:lYrun3JOyT0wpMEOA6bPDKVGYsxCHOUHUwczE0VNySQ=,tag:ue2n56zQkpSgx1zAwSY7EA==,type:str]
    username: ENC[AES256_GCM,data:CxVJlohsgbECUS4M,iv:WlahRKOUcBVPBzsCCAvn482xwHd17IULHeLeRb/+TDc=,tag:Id5/MWNQ6bjeXiueKB844Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-cnpg-creds
    namespace: keycloak
    labels:
        cnpg.io/reload: "true"
sops:
    lastmodified: "2025-09-22T08:59:35Z"
    mac: ENC[AES256_GCM,data:1BWaYlRMHAmRCIKeaUogu13MO7IeJZstTUGxTAxy5sKPEfdLoMu38FkJAjBAHt7nyEdSxlvXA83XpNEEHm3MK7kNdXzeByGBal9bNRsaH6jzxLuUTCigNk56E/bo3/a9hPTobYFYtD1QLlv8tgY2tEzr2KQC1duePxwKK0SmZW0=,iv:mipfvkc36kjVFeRGTt3UM8fk5WEyNVVMSZ1Uin9Jzjg=,tag:HA8DE88kZbxIXgBuUtGk6g==,type:str]
    pgp:
        - created_at: "2025-09-22T08:59:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWK9rONmXZEsSAQdAEu/RhcxRlINDBOCsq4YPIK8p84gsv7wiRzjErsLk8Tgw
            ToFDqWbjg+VRssRq5GH73itb0tdZbXOlLplN9nvO7m1PAzBunmy+Ys4QJufLSR4R
            1GgBCQIQIgSF6DvG1hbXA3aGu26o4r8Oh1vNXsjGQFR9Z7DCD3jCJ1UzuLANLnPa
            JOyHqkTLeJfFhvs7EOdFWwS/e11wbPRLxre14VPPSr01mBVEWvoOnZm2bHXmmDJr
            1XOwUuFAeTeLqA==
            =Ud0v
            -----END PGP MESSAGE-----
          fp: BC3A767578FF432C7414DE6A73A07B99E207F7AF
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
