apiVersion: v1
data:
    key: ENC[AES256_GCM,data:s5UEp5LkA4EmbYQ3QPz7XFcmIiuex8FDyYBu+V2j9Jx8MXrmwfr2HCLknYM=,iv:uuwXqHB864tbyZRVvapVOvP1PtFxHSyqnXBuWcAL68g=,tag:jv78yRr5LQ6WMG2JO8dZLQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: optimiser-internal-client-secret
    namespace: optimiser
sops:
    lastmodified: "2025-04-11T14:30:57Z"
    mac: ENC[AES256_GCM,data:ETSBtXS0SdoyjCPhNn+o+leKIL6nggERVyTkoacg48IK+nDgTn3dzo4sUtyB3/8dmmXiXa7lC4hSEesqw73/UA7rHRlNElusEC4iB6qsLkqm12Z4V0wYPusobgRQjbBgA/G3t9LSeT7eMyYLDU4ra1oYOnpd+cz23wcJqhQU/lo=,iv:FUyB+EsSUg67N7vyEar7nVfLO4EeZoIIvq1fqIQPQF4=,tag:AjMa+m8EHqErPuSWBG1SJw==,type:str]
    pgp:
        - created_at: "2025-04-11T14:30:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWK9rONmXZEsSAQdAsXGAkGqBG13YWXJrEClzY+VpbFeYOSMt4q94LD/UCm4w
            YHRqkmIS361SaMAVWtDxAaXCGkM/K5eZNdovwPPx5TOSLq8K5NxvgexduMUfGvQu
            1GgBCQIQdOm+yOiv/m1Q0PhRofyC42jLZQMk1cW7RbPJ0BwHq95fUSy/MbL2nJnF
            IDnTWBvxn6W7Rew2WDhyJBHBDuRtTTkLfVoc53O5QN2JgSONBOd6YZEogpGlm0ON
            itZYv4lauMlrpw==
            =hyww
            -----END PGP MESSAGE-----
          fp: BC3A767578FF432C7414DE6A73A07B99E207F7AF
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
