apiVersion: v1
data:
    password: ENC[AES256_GCM,data:1tf1dYA7E2SXmZKMLeIssHNBXaK+eHLG5SNRiH5YeI/OW54cpVXHnqoVNZusFqOB,iv:CWfV5l4xmikf13RSI09CXmTFb7G6iipyFHOMnnJ2usw=,tag:4GZwcN2v6OtlS3sgZp1Mkw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: optimiser-attachment-postgres-creds
    namespace: optimiser
sops:
    lastmodified: "2025-04-11T14:30:57Z"
    mac: ENC[AES256_GCM,data:lEfnRnzndp+neHMH5S8dRnvAzi9dRFd+MON5GZxjtHyKN2gS9XMruigxkCDeg/end/DHhAXv7XxzbWf29ko3KBwnG+hB59GKmBHxJVRsaoXBt3w4UNOKudxxSVZ1Eeugo936UYKSBaOylFjHWvwOH8qN8SQC6g8DlPNv34ejo2E=,iv:JzA1rYUkQzUSnPJA+M7YrcLyi7Ki/0ZfTrYPFjPX4i4=,tag:m/+2wKTZZMr0OL5kEeCSHA==,type:str]
    pgp:
        - created_at: "2025-04-11T14:30:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWK9rONmXZEsSAQdAygCm1cI+CLkIhU626jtQ7YS6lQB9wFWSGfOkgzYVJxsw
            qihzANY0YdKxuDDlYrsXUyiH4yYjgjXZJqIKxiKiit6WJH2rQRcLDpNfTvLUJo+7
            1GgBCQIQ/NcHAkm3kYF3R2P7KYwLS5Iw9pprCwXAb01INzWwVCR7LpJYDtV5v/aE
            kxg5RSphPXfpK5rNbNR9eIiYiokD0K0CLNzoc5epNn3aBmxlr07giu1Ce0qK4kX3
            AfSHHqcaObAl3w==
            =8MWI
            -----END PGP MESSAGE-----
          fp: BC3A767578FF432C7414DE6A73A07B99E207F7AF
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
