apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:SshzPt2jXv/vofUdMSxLHk1s8bKQmCaCa6N4xN2cnwIbg4lNeGyk21VvVh8WnYN14eLW9nfsJflmCGuZE8N8vdXbXJmWCxTRaHXay8pREW1YW6YhkBp0Fm1m0T5YbA14rHPYAGPIGhI=,iv:BSKp4IQTCYS7W1wHDTlbNW0c0AbZpHWp8ovYiu/q2xE=,tag:Ots2C5lH7LDsx83TvyBRJA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: blue-demandb-authority-account
    namespace: demandb
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-12T15:00:30Z"
    mac: ENC[AES256_GCM,data:ea0oVL5emLY1dfrAvG8348fykJOvMFekB8KX1qTz2dEQKHuU+QiB5SGdnGVDo7d8sLl2nPx5kuT1PcqMHfBZV0yEA2itfeEuz7fOAWmawJO+/empQXfGkeS1oh8KCz9POhqogmr2FRc5AVbza+gvdrDLjz/7fK3R4C51g0Hk/oc=,iv:ozvwWH3c9oX1/fh7ma/KT7Qsc2ldJQrl+nt8QMIBOcQ=,tag:FLFc1kzE1rdbpay0nSMg7w==,type:str]
    pgp:
        - created_at: "2025-03-12T15:00:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAOgs9qqqq+4vAdlEJ1f7NRRibxRlCEKq6dQ1LZvb+2RIw
            mF1afOeal6wExGKYqwL8SCNW7COltSKcyqlcNpo+XNhJuLW7sDxVnL7FjEhHWHXC
            1GgBCQIQ/bRKwMC0oYyKNqv4dRXo9yPJir/l2glWHr0Err+qDkYxoGsjMxdvLUjg
            RUHmLiukwz9YGM1SRw+jyGOyT1hZX6+1AtI5IsRG+iRQRBKfhreJwiFF8jnVfdeg
            c6tloN+GxoM0+Q==
            =skR+
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
