apiVersion: v1
data:
    password: ENC[AES256_GCM,data:08+UGM1702Kg9TC5tWdOkpiQ8P3U88ddfFnH/jBZjU8y48gHrpg6gyGVkRLmzSM8,iv:LTz529BWZBujxQ/X/gskf1cxn/H9XU3euN6IzNCYaqA=,tag:rdcxUypK7gvdKAqvfeAMYQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: demandb-attachment-postgres-creds
    namespace: demandb
sops:
    lastmodified: "2025-04-10T13:05:43Z"
    mac: ENC[AES256_GCM,data:ey1VN1eWQZlIvbDYWezHaJXAjGV+Cqrn7Dr4zzXij6oJwL2jgEYCUk+qvl1UCYEN2ilxhKLVuPLzTJj2OrPl9YPEX+l5O4/0xk1jWdEYh/8Jjr8JX9OFmlRuiK2UM6PBbR6EzggiUopeLwRSQS9WC5todsG7DzH4SgPU9rbGeUY=,iv:Q5oU/n+f0dTgi3AN2oMWAtUv9lHz5jT/2Bmgb4hTRvY=,tag:ebp4t2S41cIe3HT/df6EfA==,type:str]
    pgp:
        - created_at: "2025-04-10T13:05:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAgsyeGTizVy5CQX2URTDkBgmJ5J6C9asIMpm7zx0vcEYw
            CjhyjPKihr3mh/5fQNoyr4FhRh5i0shiQXdxShR+tPj882zKaP/2AloGBFmpGivL
            1GgBCQIQkVvEyJTi44SghJWtT9z/jDW3ezpkDDqn8TxRR4+bbGxeK1caetGJ9FUP
            rkcFw2WDKmxvX7tP6Dqx3pR9iKXbs8UP5Qiu4cannKbiHmJBFiYFfx297IYav8WY
            sIQvrlzNmEz0FA==
            =HbUd
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
