apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4uhKXRwyyXQTTz1+qwEWE8GOg9lxWRh7rbY7q+TOI4DB/jxFamFqRFyykdcQ2FOZ,iv:+C1um8nNX2/A+eyV72P7/yxOPW5pjr0fhaFbLN/LmeA=,tag:SW41Owxjtu9F8X3N5CECsQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: demanda-attachment-postgres-creds
    namespace: demanda
sops:
    lastmodified: "2025-04-10T13:05:43Z"
    mac: ENC[AES256_GCM,data:6dBL0BK0zzGveKwpxYvlIPTWlxLwaKd2XPcaZcob6a5dA/WP51zzUYGzR0ZC8P/159ALTfp1vct2MVN07wvs2Z4SiLH+GXtUlXkLJJcP58rAoL5XNgg5C2of5AAJjS9AjTvH4Sd4MVu1faJ2IGlkV0jQW3RnBTRyZMiLmGsrBYA=,iv:VUQihGU5z27HpHCPEEMGcrXsqPSHmUTVzD9qfZW3MRc=,tag:vU9JW2MsA1P8ASq2XzG7og==,type:str]
    pgp:
        - created_at: "2025-04-10T13:05:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAgtJpN6iK6YgNErt5qOcyDwSGvsP3/wngoYYW/0RjVHUw
            MH2JsfXsRyX0ltDtYHik1/nP/3wFxcpbi4IHj27cnnnPuGhGoqQnjwMhsVrm/lfQ
            1GgBCQIQSnJdX4G/MviV1Obkko2aIVXT5SPEce1Yt8rz5mggnvICqAmHqTZ+2VEN
            JM8wsp5vkWyPWpleyFkNVpJYF3ttgpBWcghZLOWCiQHQDHKZvntKGowqFeVbaF1A
            Oo1jshmXnQjF9A==
            =7mNC
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
