apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:Pg+jYigr0L9JrkswO33m/kRw+UTXtXf9CiDpjHo8aCT8qa1jBnqyGkG2mRKaPlIkX/7VULJob1NjhBWVq+f5KgnSYIAMFjKH3kd1nr8ltuu70x5Gc6BwzCc8Pop1d+ZH,iv:ZHViqII5+Osy4RWfyy9uAVxWtUpsiNT6hamV4p10fgc=,tag:B4u693z1BaYPIZHtGvbvPQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: green-match2-authority-account
    namespace: match2
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-12T15:00:31Z"
    mac: ENC[AES256_GCM,data:zT3FoM7kv4PQWYnXYiQMt7DWbA+X6Tdpgb3IfwrvVkWOToazP7GQ1AyHtgfwEk9apm0iGTTNdm+p7S2nX0OAQEGLUlCh/ev/IGdp3/EMa7kgHG/Rutbff9lXkPHFZHOi5vwFHNMQVQNGQZevBjo5BsPLBy80bKuhicMXvJjlbg0=,iv:gnrtq/WXyJB4zuUgg4G0crt9l1ybZSLpjgZUWddA6jU=,tag:jl76hCa2i8kHHHJ461tLdA==,type:str]
    pgp:
        - created_at: "2025-03-12T15:00:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUwQKXS8ls7oSAQdAF36rJNKfeXD+X5/hEA+m8Kr38DhuyG/YA5nRDZxTq2Mw
            LiEsOeV+FlfFRLZq0wlLpk8w6f5TwN23g5Rv2eLf8ezrvO41yOL+MsSJdurp+YLh
            1GgBCQIQtthT0rEkq46ypOPpHrbURsS5yX/yzdOy7sqE1tv+lxo1g3tUr+BdcBGw
            3mqDYyMZOokrByVFYTLwCGolmOeJwsBEfgONK7kPAB4yXIFflK3gXENGFLA8VdwW
            AKp71bRJFvBthQ==
            =Z2UA
            -----END PGP MESSAGE-----
          fp: 025EED3A1FBD8A5CE8A150C56DC71B2AE79A5F9B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
