# https://github.com/codecentric/helm-charts/blob/master/charts/keycloakx/values.yaml
nameOverride: "keycloak"
proxy:
  enabled: true
  mode: forwarded
ingress:
  enabled: true
  ingressClassName: nginx-keycloak
  rules:
    - host: auth.sqnc-stage.com
      paths:
        - path: "/"
          pathType: Prefix
http:
  relativePath: "/"
extraEnv: |
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: admin
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-creds
        key: password
  - name: KC_HOSTNAME_ADMIN
    value: "https://auth.sqnc-stage.com/"
  - name: KC_HOSTNAME
    value: "https://auth.sqnc-stage.com/"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
metrics:
  enabled: true
serviceMonitor:
  enabled: true
  namespace: keycloak
  relabelings:
    - action: replace
      sourceLabels: [namespace]
      targetLabel: kubernetes_namespace
database:
  existingSecret: keycloak-postgres-password
  existingSecretKey: password
  vendor: postgres
  hostname: cluster-rw.keycloak.svc.cluster.local
  port: 5432
  database: keycloak
  username: keycloak
podAnnotations:
    instrumentation.opentelemetry.io/inject-java: "monitoring/java-instrumentation"
