global:
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/keycloak
keycloakConfigCli:
  image:
    repository: bitnamilegacy/keycloak-config-cli
production: true
proxyHeaders: forwarded
ingress:
  enabled: true
  ingressClassName: nginx-keycloak
  hostname: auth.sqnc-stage.com
adminIngress:
  enabled: true
  ingressClassName: nginx-keycloak
  hostname: auth.sqnc-stage.com
auth:
  adminUser: "admin"
extraEnvVars:
  - name: KC_HOSTNAME_ADMIN
    value: "https://auth.sqnc-stage.com/"
  - name: KC_HOSTNAME
    value: "https://auth.sqnc-stage.com/"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: keycloak
    relabelings:
      - action: replace
        sourceLabels: [namespace]
        targetLabel: kubernetes_namespace
postgresql:
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  global:
    security:
      allowInsecureImages: true
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
  serviceMonitor:
    enabled: true
    namespace: keycloak
    relabelings:
      - action: replace
        sourceLabels: [namespace]
        targetLabel: kubernetes_namespace
podAnnotations:
    instrumentation.opentelemetry.io/inject-java: "monitoring/java-instrumentation"