logLevel: info
selfAddress: 5CBBTHTaV1VkcCoaRcaPJnQZwGusNgamRkE8ZBzXwkpZvjho
externalSqncNode:
  host: sqnc-node
  port: 9944
auth:
  clientId: 'sqnc'
  publicIdpOrigin: "https://auth.sqnc-stage.com/"
  internalIdpOrigin: "http://keycloak-http.keycloak.svc.cluster.local"
  idpPathPrefix: ""
  oauth2Realm: demanda
  internalRealm: demanda-internal
ingress:
  enabled: true
  ingressClassName: nginx-demanda
  hostname: demanda.sqnc-stage.com
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  global:
    security:
      allowInsecureImages: true
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: demanda
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"