logLevel: debug
externalSqncNode:
  host: sqnc-node
  port: 9944
externalSqncIpfs:
  host: ipfs-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: match2-identity-service-sqnc-identity-service
  port: 3000
externalSqncAttachment:
  host: match2-sqnc-attachment-api
  port: 3000
auth:
  clientId: 'sqnc'
  publicIdpOrigin: "https://auth.sqnc-stage.com/"
  internalIdpOrigin: "http://keycloak-http.keycloak.svc.cluster.local"
  idpPathPrefix: ""
  oauth2Realm: match2
  internalRealm: match2-internal
  internalClientId: sqnc
ingress:
  enabled: true
  ingressClassName: nginx-match2
  hostname: match2.sqnc-stage.com
node:
  enabled: false
postgresql:
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  global:
    security:
      allowInsecureImages: true
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 15Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: match2
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
tests:
  auth:
    clientId: sqnc
  osShell:
    image:
      repository: bitnamilegacy/os-shell
