---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: teams-bot
  namespace: monitoring
spec:
  type: msteams
  secretRef:
    name: teams-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: msteams
  namespace: monitoring
spec:
  providerRef:
    name: teams-bot
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: flux-system
    - kind: Kustomization
      name: '*'
      namespace: 'cert-manager'
    - kind: HelmRelease
      name: '*'
      namespace: 'cert-manager'
    - kind: Kustomization
      name: '*'
      namespace: 'optimiser'
    - kind: HelmRelease
      name: '*'
      namespace: 'optimiser'
    - kind: Kustomization
      name: '*'
      namespace: 'capacity'
    - kind: HelmRelease
      name: '*'
      namespace: 'capacity'
    - kind: Kustomization
      name: '*'
      namespace: 'keycloak'
    - kind: HelmRelease
      name: '*'
      namespace: 'keycloak'
    - kind: Kustomization
      name: '*'
      namespace: 'order'
    - kind: HelmRelease
      name: '*'
      namespace: 'order'
    - kind: Kustomization
      name: '*'
      namespace: 'monitoring'
    - kind: HelmRelease
      name: '*'
      namespace: 'monitoring'
