logLevel: info
paths:
  - http://charlie-identity-service-sqnc-identity-service:3000/api-docs
  - http://charlie-sqnc-matchmaker-api:3000/api-docs
  - http://charlie-sqnc-attachment-api:3000/api-docs
baseUrl:
  - http://localhost:3080/charlie/
apiPublicUrlPrefix: /charlie
oauthClientId: "sequence"
oauthAppName: "Charlie Swagger"
oauthUsePkce: true
ingress:
  hostname: localhost
  paths:
    - path: /charlie/(api-docs(/.*)?)
      pathType: Prefix
    - path: /charlie/(swagger(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
securitySchema:
  name: "oauth2"
  type: "oauth2"
  enabled: true
  oauth2:
    flows:
      - clientCredentials
    tokenUrl: "/auth/realms/charlie/protocol/openid-connect/token"
    refreshUrl: "/auth/realms/charlie/protocol/openid-connect/token"
    scopes: 
      demandA:read: "Read demandA"
      demandA:prepare: "Prepare demandA"
      demandA:create: "Create demandA"
      demandA:comment: "Comment on demandA"
      demandB:read: "Read demandB"
      demandB:prepare: "Prepare demandB"
      demandB:create: "Create demandB"
      demandB:comment: "Comment on demandB"
      match2:read: "Read match2"
      match2:prepare: "Prepare match2"
      match2:propose: "Propose match2"
      match2:cancel: "Cancel match2"
      match2:accept: "Accept match2"
      match2:reject: "Reject match2"
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
