node:
  chain: local
  role: validator
  dataVolumeSize: 1Gi
  customNodeKey: "0000000000000000000000000000000000000000000000000000000000000001"
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  flags:
    - "--rpc-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"
    - "--alice"
    - "--prometheus-external"
  serviceMonitor:
    enabled: true
    namespace: monitoring
storageClass: standard
tests:
  osShell:
    image:
      repository: bitnamilegacy/os-shell
kubectl:
  image:
    repository: bitnamilegacy/kubectl