apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: jaeger
      version: "4.4.7"
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
      valuesKey: values-jaeger.yaml
