provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
esIndexCleaner:
  enabled: true
  image:
    repository: jaegertracing/jaeger-es-index-cleaner
    pullPolicy: IfNotPresent
    tag: "1.69"
  schedule: "*/5 * * * *"
  numberOfDays: 30
  serviceAccount:
    create: true
    name:
