provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
esIndexCleaner:
  enabled: false
  image:
    repository: jaegertracing/jaeger-es-index-cleaner
    pullPolicy: IfNotPresent
    tag: "latest"
  schedule: "0 10 * * *"
  numberOfDays: 30
  serviceAccount:
    create: false
    name: jaeger
