---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capacity-attachment-api
  namespace: capacity
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
    - name: ipfs-capacity
    - name: capacity-identity-service
  chart:
    spec:
      chart: sqnc-attachment-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: 3.1.15
  valuesFrom:
    - kind: ConfigMap
      name: capacity-values
      valuesKey: values-attachment-api.yaml
    - kind: Secret
      name: capacity-attachment-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: capacity-internal-client-secret
      valuesKey: key
      targetPath: auth.internalClientSecret
    - kind: Secret
      name: capacity-keys
      valuesKey: account_seed
      targetPath: userUri
  interval: 10m0s
