logLevel: debug
externalSqncNode:
  host: sqnc-node
  port: 9944
externalSqncIpfs:
  host: ipfs-capacity-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: capacity-identity-service-sqnc-identity-service
  port: 3000
auth:
  clientId: 'l3'
  publicIdpOrigin: "https://auth.dsch-l3.com"
  internalIdpOrigin: "http://keycloak.keycloak.svc.cluster.local"
  idpPathPrefix: /auth
  oauth2Realm: capacity
  internalRealm: capacity-internal
  internalClientId: l3
ingress:
  enabled: true
  ingressClassName: nginx-capacity
  hostname: capacity.dsch-l3.com
node:
  enabled: false
postgresql:
  global:
    imagePullSecrets:
      - name: dockerhub
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 15Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: capacity
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
