externalSqncNode:
  host: sqnc-node
  port: 9944
ipfs:
  bootNodeAddress: /dns4/ipfs-sqnc-ipfs-0-swarm.demanda.svc.cluster.local/tcp/4001/p2p/12D3KooWFjV75AharhHUtuYQuUji7VjDUTi7beL5dR26ucszBTfb
persistence:
  storageClass: managed-csi-premium
  size: 60Gi
sqncNode:
  enabled: false
podAnnotations:
  instrumentation.opentelemetry.io/inject-sdk: "monitoring/go-instrumentation"
securityContext:
  privileged: true
  runAsUser: 0
extraEnvVars:
  - name: IPFS_TRACING
    value: "true"
  - name: OTEL_TRACES_EXPORTER
    value: "otlp"