---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demanda-matchmaker-api
  namespace: demanda
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
    - name: ipfs
    - name: demanda-identity-service
  chart:
    spec:
      version: 4.0.2
      chart: sqnc-matchmaker-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: demanda-values
      valuesKey: values-matchmaker-api.yaml
    - kind: Secret
      name: demanda-matchmaker-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: demanda-matchmaker-internal-client-secret
      valuesKey: secret
      targetPath: auth.internalClientSecret
    - kind: Secret
      name: demanda-keys
      valuesKey: account_seed
      targetPath: userUri
  interval: 10m0s
