logLevel: info
selfAddress: 5HdXyANz5ySq8FPBxhdbm2d8FjPRKZHEAnNtypaAWix8BDRJ
externalSqncNode:
  host: sqnc-node
  port: 9944
auth:
  clientId: 'l3'
  publicUrlPrefix: "https://auth.dsch-l3.com"
  internalUrlPrefix: "http://keycloak.keycloak.svc.cluster.local"
  idpPathPrefix: /auth
  oauth2Realm: optimiser
  internalRealm: optimiser-internal
ingress:
  enabled: true
  ingressClassName: nginx-optimiser
  hostname: optimiser.dsch-l3.com
node:
  enabled: false
postgresql:
  global:
    imagePullSecrets:
      - name: dockerhub
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: optimiser
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
global:
  imagePullSecrets:
    - name: dockerhub
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
