apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - source.yaml
  - monitoring-pod-monitor-sync.yaml
  - kube-prometheus-stack
  - otel
  - jaeger
  - nginx
  - redis
configMapGenerator:
  - name: monitoring-values
    files:
      - values-nginx.yaml=nginx/values.yaml
      - values-monitoring.yaml=kube-prometheus-stack/values.yaml
      - values-opentelemetry.yaml=otel/values.yaml
      - values-jaeger.yaml=jaeger/values.yaml
      - values-otel.yaml=otel/values.yaml
      - values-redis.yaml=redis/values.yaml
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: flux-grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
