---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: charlie-sqnc-attachment-api
  namespace: charlie
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  test:
    enable: true
  dependsOn:
    - name: charlie-node
    - name: charlie-ipfs
    - name: charlie-identity-service
  chart:
    spec:
      chart: sqnc-attachment-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: "2.0.4"
  valuesFrom:
    - kind: ConfigMap
      name: charlie-values
      valuesKey: values-sqnc-attachment-api.yaml
  interval: 10m0s
