---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: optimiser-matchmaker-api
  namespace: optimiser
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  test:
    enable: false
  dependsOn:
    - name: ipfs-optimiser
    - name: optimiser-identity-service
  chart:
    spec:
      version: 4.0.15
      chart: sqnc-matchmaker-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: optimiser-values
      valuesKey: values-matchmaker-api.yaml
    - kind: Secret
      name: optimiser-matchmaker-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: optimiser-internal-client-secret
      valuesKey: key
      targetPath: auth.internalClientSecret
    - kind: Secret
      name: optimiser-client-secret
      valuesKey: key
      targetPath: tests.auth.clientSecret
    - kind: Secret
      name: optimiser-keys
      valuesKey: account_seed
      targetPath: userUri
  interval: 10m0s
