logLevel: debug
externalSqncNode:
  host: sqnc-node
  port: 9944
externalSqncIpfs:
  host: ipfs-optimiser-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: optimiser-identity-service-sqnc-identity-service
  port: 3000
externalSqncAttachment:
  host: optimiser-attachment-api-sqnc-attachment-api
  port: 3000
auth:
  clientId: 'l3'
  publicIdpOrigin: "https://auth.dsch-l3.com"
  internalIdpOrigin: "http://keycloak-http.keycloak.svc.cluster.local"
  idpPathPrefix: ""
  oauth2Realm: optimiser
  internalRealm: optimiser-internal
  internalClientId: l3
ingress:
  enabled: true
  ingressClassName: nginx-optimiser
  hostname: optimiser.dsch-l3.com
node:
  enabled: false
postgresql:
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  global:
    imagePullSecrets:
      - name: dockerhub
    security:
      allowInsecureImages: true
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 15Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: optimiser
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
global:
  imagePullSecrets:
    - name: dockerhub
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
tests:
  auth:
    clientId: l3
  osShell:
    image:
      repository: bitnamilegacy/os-shell
