---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: match2-identity-service
  namespace: match2
spec:
  dependsOn:
    - name: green-node
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      version: 5.1.19
      chart: sqnc-identity-service
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: match2-values
      valuesKey: values-identity-service.yaml
    - kind: Secret
      name: match2-identity-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: match2-internal-client-secret
      valuesKey: key
      targetPath: auth.internalClientSecret
  interval: 10m0s
