---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bob-node
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  test:
    enable: true
  chart:
    spec:
      chart: sqnc-node
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: "7.1.7"
  valuesFrom:
    - kind: ConfigMap
      name: bob-values
      valuesKey: values-sqnc-node.yaml
  interval: 10m
