apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster
  namespace: keycloak
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  releaseName: cluster
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      version: "0.5.0"
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: cluster-values
      valuesKey: values.yaml
