apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "6.53.0"
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
      valuesKey: values-loki.yaml
