---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demandb-identity-service
  namespace: demandb
spec:
  dependsOn:
    - name: blue-node
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      version: 5.1.20
      chart: sqnc-identity-service
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: demandb-values
      valuesKey: values-identity-service.yaml
    - kind: Secret
      name: demandb-identity-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password      
  interval: 10m0s
