---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ipfs-optimiser
  namespace: optimiser
spec:
  dependsOn:
    - name: yellow-node
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      version: 4.0.36
      chart: sqnc-ipfs
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: optimiser-values
      valuesKey: values-ipfs.yaml
  interval: 10m
