externalSqncNode:
  host: sqnc-node
  port: 9944
ipfs:
  bootNodeAddress: /dns4/ipfs-capacity-sqnc-ipfs-0-swarm.capacity.svc.cluster.local/tcp/4001/p2p/12D3KooWLMN2Afe5e6WcoAQKDsmhzPxj1YuDGKhn9T4vgVmwu9Vz
persistence:
  storageClass: managed-csi-premium
  size: 60Gi
sqncNode:
  enabled: false
global:
  imagePullSecrets:
    - name: dockerhub
podAnnotations:
  instrumentation.opentelemetry.io/inject-sdk: "monitoring/go-instrumentation"
securityContext:
  privileged: true
  runAsUser: 0
extraEnvVars:
  - name: IPFS_TRACING
    value: "true"
  - name: OTEL_TRACES_EXPORTER
    value: "otlp"