logLevel: info
selfAddress: 5Df4d56pDyPz3RM3RBLYC7nyhhL9mGXchrV1dkyYPt5u8H88
externalSqncNode:
  host: sqnc-node
  port: 9944
auth:
  clientId: 'l3'
  publicIdpOrigin: "https://auth.dsch-l3.com"
  internalIdpOrigin: "http://keycloak.keycloak.svc.cluster.local"
  idpPathPrefix: ""
  oauth2Realm: order
  internalRealm: order-internal
ingress:
  enabled: true
  ingressClassName: nginx-order
  hostname: order.dsch-l3.com
node:
  enabled: false
postgresql:
  global:
    imagePullSecrets:
      - name: dockerhub
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: order
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
global:
  imagePullSecrets:
    - name: dockerhub
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
