apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - keycloak
  - nginx
  - cluster
  - source.yaml
configMapGenerator:
  - name: keycloak-values
    files:
      - keycloak-values.yaml=keycloak/values.yaml
      - nginx-values.yaml=nginx/values.yaml
      - cluster-values.yaml=cluster/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
