---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ipfs-order
  namespace: order
spec:
  dependsOn:
    - name: blue-node
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      version: 4.0.36
      chart: sqnc-ipfs
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: order-values
      valuesKey: values-ipfs.yaml
  interval: 10m
