externalSqncNode:
  host: sqnc-node
  port: 9944
persistence:
  storageClass: managed-csi-premium
  size: 60Gi
sqncNode:
  enabled: false
podAnnotations:
  instrumentation.opentelemetry.io/inject-sdk: "monitoring/go-instrumentation"
securityContext:
  privileged: true
  runAsUser: 0
extraEnvVars:
  - name: IPFS_TRACING
    value: "true"
  - name: OTEL_TRACES_EXPORTER
    value: "otlp"