---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alice-identity-service
  namespace: alice
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: alice-node
  chart:
    spec:
      chart: sqnc-identity-service
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: "5.1.145"
  valuesFrom:
    - kind: ConfigMap
      name: alice-values
      valuesKey: values-sqnc-identity-service.yaml
  interval: 10m0s
