logLevel: info
selfAddress: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
externalSqncNode:
  host: alice-node-sqnc-node-0
  port: 9944
auth:
  clientId: 'sequence'
  publicUrlPrefix: "http://localhost:3080/auth/realms/alice/protocol/openid-connect"
  internalUrlPrefix: "http://keycloak.keycloak.svc.cluster.local/auth/realms/alice/protocol/openid-connect"
ingress:
  hostname: localhost
  paths:
    - path: /alice/(v1/members(/.*)?)
      pathType: Prefix
    - path: /alice/(v1/self(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
node:
  enabled: false
postgresql:
  auth:
    password: postgres
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
  primary:
    containerSecurityContext:
      readOnlyRootFilesystem: false
    extraVolumeMounts:
      - name: postgres-upgrade
        mountPath: /mnt/upgrade
    extraVolumes:
      - name: postgres-upgrade
  extraDeploy:
    - apiVersion: batch/v1
      kind: Job
      metadata:
        name: alice-sqnc-identity-service-postgresql-17
        namespace: alice
      spec:
        template:
          spec:
            securityContext:
              fsGroup: 1001
              runAsUser: 1001
            initContainers:
              - name: pgdump-17
                image: bitnami/postgresql:17
                imagePullPolicy: IfNotPresent
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1001
                command:
                  - /bin/sh
                  - -c
                args:
                  - |
                    pg_dump -d postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$HOST:$POSTGRESQL_PORT_NUMBER/$POSTGRES_DATABASE -f /mnt/upgrade/pg_dump
                volumeMounts:
                  - name: postgres-upgrade
                    mountPath: /mnt/upgrade
                env:
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: alice-sqnc-matchmaker-api-postgresql
                        key: password
                  - name: POSTGRES_USER
                    value: identity_service
                  - name: POSTGRES_DATABASE
                    value: user
                  - name: POSTGRESQL_PORT_NUMBER
                    value: "5432"
                  - name: HOST
                    value: alice-sqnc-identity-service-postgresql
            containers:
              - name: psql-17
                image: bitnami/postgresql:17
                imagePullPolicy: IfNotPresent
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1001
                command:
                  - /bin/sh
                  - -c
                args:
                  - |
                    psql -d postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$HOST:$POSTGRESQL_PORT_NUMBER/$POSTGRES_DATABASE -f /mnt/upgrade/pg_dump
                    mkdir -p /mnt/upgrade/tmp/
                    cp -R /opt/bitnami/postgresql /mnt/upgrade/tmp/
                volumeMounts:
                  - name: postgres-upgrade
                    mountPath: /mnt/upgrade
                env:
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: alice-sqnc-matchmaker-api-postgresql
                        key: password
                  - name: POSTGRES_USER
                    value: identity_service
                  - name: POSTGRES_DATABASE
                    value: user
                  - name: POSTGRESQL_PORT_NUMBER
                    value: "5432"
                  - name: HOST
                    value: alice-sqnc-identity-service-postgresql
            volumes:
              - name: postgres-upgrade
            restartPolicy: Never
      restartPolicy: Never
      backoffLimit: 0
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
