---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: order-matchmaker-api
  namespace: order
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  test:
    enable: false
  dependsOn:
    - name: ipfs-order
    - name: order-identity-service
  chart:
    spec:
      version: 4.0.15
      chart: sqnc-matchmaker-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
    - kind: ConfigMap
      name: order-values
      valuesKey: values-matchmaker-api.yaml
    - kind: Secret
      name: order-matchmaker-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: order-internal-client-secret
      valuesKey: key
      targetPath: auth.internalClientSecret
    - kind: Secret
      name: order-client-secret
      valuesKey: key
      targetPath: tests.auth.clientSecret
    - kind: Secret
      name: order-keys
      valuesKey: account_seed
      targetPath: userUri
  interval: 10m0s
